{
 "title": "Leistungsdashboard",
 "time": { "from": "2026-01-23T23:00:00.000Z", "to": "2026-01-24T22:59:59.000Z" },
 "panels": [
  {
   "title": "Temperaturvergleich WP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "WP Vorlauf WMZ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "wmz_wp_vorlauf" }
     ]
    },
    {
     "alias": "WP Vorlauf Außenwand",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "warmepumpe_vl_aussenwand" }
     ]
    },
    {
     "alias": "WP Rücklauf WMZ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "wmz_wp_rucklauf" }
     ]
    },
    {
     "alias": "WP Rücklauf Außenwand",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "warmepumpe_rl_aussenwand" }
     ]
    },
    {
     "alias": "WP Monoblock",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "warmepumpe_vl_monoblock" }
     ]
    }
   ]
  },
  {
   "title": "Validierung der Bivalenten Schaltung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "wirtschaftlicher Bivalenzpunkt",
     "query": "SELECT (mean(\"value\") * 0) + (0.3 / 0.088 * 0.95) AS \"Umschalt COP (Grenze)\" \nFROM \"cop_prognose\" \nWHERE (\"entity_id\"::tag = 'influx_wp_cop_prognose') \nAND $timeFilter \nGROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "COP Prgonose",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cop_prognose",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "influx_wp_cop_prognose" }
     ]
    },
    {
     "alias": "Gastherme Relais",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch.gas_relais",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "gas_relais" }
     ]
    },
    {
     "alias": "Wärmepumpe Relais",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch.wp_relais",
     "query": "SELECT last(\"value\") FROM \"switch.wp_relais\" WHERE (\"entity_id\"::tag = 'wp_relais') AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "wp_relais" }
     ]
    }
   ]
  },
  {
   "title": "Temperatur Pufferspeicher - Außentemperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "H5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "thermometer_pufferspeicher_h5" }
     ]
    },
    {
     "alias": "H4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "thermometer_pufferspeicher_h4" }
     ]
    },
    {
     "alias": "H1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "thermometer_pufferspeicher_h1" }
     ]
    },
    {
     "alias": "Außen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "thermometer_aussen" }
     ]
    }
   ]
  },
  {
   "title": "WP Leistungsaufnahme - Leistungsabgabe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "WP Leistungsaufnahme (Elektrisch)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "shelly_wp_power" }
     ]
    },
    {
     "alias": "WP Leistungsabgabe (Thermisch)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "wmz_wp_power" }
     ]
    },
    {
     "alias": "Resultierende COP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cop_prognose",
     "query": "SELECT mean(\"value\") FROM \"cop_prognose\" WHERE (\"entity_id\"::tag = 'influx_wp_cop_prognose') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "influx_wp_cop_prognose" }
     ]
    }
   ]
  },
  {
   "title": "WP Freigabenvalidierung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "WP Leistungsaufnahme (Elektrisch)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "shelly_wp_power" }
     ]
    },
    {
     "alias": "WP Leistungsabgabe (Thermisch) (kW)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "wmz_wp_power" }
     ]
    },
    {
     "alias": "WP Relais (0/1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "switch.wp_relais",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "wp_relais" }
     ]
    }
   ]
  }
 ]
}